default: &default
  adapter: postgresql
  timeout: 5000
  database: app_development
  pool: 5
  host: db
  port: 5432
  username: postgres
  password:

development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production